language: cpp
compiler:
- gcc
deploy:
  provider: biicode
  user: kittikun
  password:
    secure: EwX/8X4UKKumrKpO6EzH0mCCeg4911tKHJybTX5Ek3MY0lYfK09i6d5hvEvjnUWbWCODqOEqIaBNJ1vBass2blx40eSmYsWLfn/X3P1fI7X7x/B6uhDlw+CNKGI3V7/8cXwW98q8R1YiMc0zwsNyCv4ak/tWbvOHnjm1eGl2Lzs=
  on:
    tags: true
    repo: kittikun/dominionrules
    branch: develop
before_install:
- echo $CXX
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- if [ "$CXX" == "g++" ]; then which g++; fi
- if [ "$CXX" == "g++" ]; then sudo apt-get install g++-4.9; fi
- if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50; fi
- if [ "$CXX" == "clang++" ]; then which clang++; fi
- if [ "$CXX" == "clang++" ]; then sudo apt-get install clang-3.5; fi
- if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/local/bin/clang++ clang++ /usr/local/bin/clang++-3.5 50; fi
install:
- wget http://www.biicode.com/downloads/latest/ubuntu64
- mv ubuntu64 bii-ubuntu64.deb
- (sudo dpkg -i bii-ubuntu64.deb) && sudo apt-get -f install
- rm bii-ubuntu64.deb
- wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
- tar -xzf cmake-3.0.2-Linux-64.tar.gz
- sudo cp -fR cmake-3.0.2-Linux-64/* /usr
script:
- cmake --version
- bii init dynxcv
- mkdir -p ./dyn/blocks/kittikun/dominionrules
- cd dyn/blocks/kittikun
- git clone https://github.com/kittikun/dominionrules.git
- cd dominionrules/build
- ./generate.py
- cd ../../../../
- bii configure
- bii build
- ./bin/kittikun_dominionrules_src_unittest_main


